# Generated by Django 5.0.7 on 2024-07-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='Время публикации')),
            ],
        ),
    ]
